# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.User'),
        ),
    ]
