# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20171112_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
